services:
  - name: telegram-bot
    type: web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: BOT_TOKEN
        sync: false
